import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

export const metadata = { title: 'Privacy Policy — MantleMandate' }

const EFFECTIVE_DATE = 'May 19, 2026'

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-page text-text-primary">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-text-secondary hover:text-text-primary transition-colors mb-10"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to home
        </Link>

        <h1 className="text-3xl font-bold text-text-primary mb-2">Privacy Policy</h1>
        <p className="text-sm text-text-secondary mb-10">Effective date: {EFFECTIVE_DATE}</p>

        <div className="prose prose-invert max-w-none space-y-8 text-[15px] leading-relaxed text-text-secondary">

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-text-primary">1. Information We Collect</h2>
            <p>We collect information you provide directly:</p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li><strong className="text-text-primary">Account data</strong> — name, email address, and hashed password.</li>
              <li><strong className="text-text-primary">Wallet addresses</strong> — public blockchain addresses you connect. We never store private keys.</li>
              <li><strong className="text-text-primary">Mandate content</strong> — the plain-English trading strategies you write.</li>
              <li><strong className="text-text-primary">Usage data</strong> — agent activity, trade records, and audit logs generated by the Service.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-text-primary">2. How We Use Your Information</h2>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>To operate and maintain the Service and your AI agents.</li>
              <li>To parse mandate policies using AI models (OpenRouter/Anthropic).</li>
              <li>To send transactional emails (agent alerts, security notifications).</li>
              <li>To detect and prevent fraud or misuse of the platform.</li>
              <li>To comply with legal obligations.</li>
            </ul>
            <p>We do not sell your personal data to third parties.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-text-primary">3. On-Chain Data</h2>
            <p>
              Transactions executed by your AI agents are recorded on the Mantle Network, a public
              blockchain. Once recorded, this data is immutable and publicly accessible. MantleMandate
              cannot delete or alter on-chain records.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-text-primary">4. Third-Party Services</h2>
            <p>We use the following third-party services that process data on our behalf:</p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li><strong className="text-text-primary">Supabase</strong> — authentication and database hosting.</li>
              <li><strong className="text-text-primary">OpenRouter / Anthropic</strong> — AI mandate parsing (mandate text is sent for processing).</li>
              <li><strong className="text-text-primary">Bybit</strong> — market data feeds (read-only API, no personal data shared).</li>
              <li><strong className="text-text-primary">The Graph</strong> — on-chain liquidity data queries.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-text-primary">5. Data Retention</h2>
            <p>
              We retain your account data for as long as your account is active. You may request account
              deletion at any time by contacting us. Audit logs and trade records linked to on-chain
              activity are retained indefinitely to support compliance and dispute resolution.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-text-primary">6. Your Rights</h2>
            <p>
              Depending on your jurisdiction, you may have the right to access, correct, or delete your
              personal data. To exercise these rights, email{' '}
              <a
                href="mailto:privacy@mantlemandate.io"
                className="text-text-link hover:text-text-link-hover transition-colors"
              >
                privacy@mantlemandate.io
              </a>
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-text-primary">7. Security</h2>
            <p>
              We use industry-standard encryption and security practices. However, no system is completely
              secure. We encourage you to use a strong password and enable two-factor authentication.
              Never share your wallet seed phrase or private keys with anyone.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-text-primary">8. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy periodically. We will notify you of material changes by
              email or a prominent notice in the application. Continued use after changes constitutes
              acceptance.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-text-primary">9. Contact</h2>
            <p>
              Privacy questions? Email{' '}
              <a
                href="mailto:privacy@mantlemandate.io"
                className="text-text-link hover:text-text-link-hover transition-colors"
              >
                privacy@mantlemandate.io
              </a>
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-border flex items-center gap-6 text-sm text-text-disabled">
          <Link href="/terms" className="hover:text-text-secondary transition-colors">Terms of Service</Link>
          <Link href="/" className="hover:text-text-secondary transition-colors">Home</Link>
        </div>
      </div>
    </div>
  )
}
