"""initial schema

Revision ID: 9d4f2fb7dbb2
Revises: 
Create Date: 2026-05-05 11:46:05.675704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d4f2fb7dbb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('ens_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('mandates',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mandate_text', sa.Text(), nullable=False),
    sa.Column('parsed_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_hash', sa.String(length=66), nullable=True),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=True),
    sa.Column('risk_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capital_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('on_chain_tx', sa.String(length=66), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mandates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mandates_policy_hash'), ['policy_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_mandates_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mandates_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('wallets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_user_id'), ['user_id'], unique=False)

    op.create_table('agents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mandate_id', sa.UUID(), nullable=True),
    sa.Column('wallet_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('capital_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('last_trade_at', sa.DateTime(), nullable=True),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('total_roi', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('drawdown_current', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_mandate_id'), ['mandate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_user_id'), ['user_id'], unique=False)

    op.create_table('alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('trades',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mandate_id', sa.UUID(), nullable=True),
    sa.Column('asset_pair', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('protocol', sa.String(length=50), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mandate_rule_applied', sa.Text(), nullable=True),
    sa.Column('gas_used', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_mandate_id'), ['mandate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_tx_hash'), ['tx_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('trade_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('decision_hash', sa.String(length=66), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_trade_id'), ['trade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tx_hash'), ['tx_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_trade_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_agent_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_user_id'))
        batch_op.drop_index(batch_op.f('ix_trades_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_trades_status'))
        batch_op.drop_index(batch_op.f('ix_trades_mandate_id'))
        batch_op.drop_index(batch_op.f('ix_trades_agent_id'))

    op.drop_table('trades')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_is_read'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_user_id'))
        batch_op.drop_index(batch_op.f('ix_agents_status'))
        batch_op.drop_index(batch_op.f('ix_agents_mandate_id'))

    op.drop_table('agents')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_user_id'))

    op.drop_table('wallets')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))

    op.drop_table('reports')
    with op.batch_alter_table('mandates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mandates_user_id'))
        batch_op.drop_index(batch_op.f('ix_mandates_status'))
        batch_op.drop_index(batch_op.f('ix_mandates_policy_hash'))

    op.drop_table('mandates')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
